// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkTMzZg6d2SDhZtqP5Kt36D10jGnJPD0U',
    appId: '1:1023534012974:web:9cb57f477e42dd0e0a9dbf',
    messagingSenderId: '1023534012974',
    projectId: 'imdf-36f5a',
    authDomain: 'imdf-36f5a.firebaseapp.com',
    storageBucket: 'imdf-36f5a.appspot.com',
    measurementId: 'G-72TK6W4CES',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlTAETzA423yIfZ1y92atED5EdKYEcLdY',
    appId: '1:1023534012974:android:4cb623ed5a9f71820a9dbf',
    messagingSenderId: '1023534012974',
    projectId: 'imdf-36f5a',
    storageBucket: 'imdf-36f5a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEtM6xoQUSmwLPv44yF1ixNKBARvJ1Nng',
    appId: '1:1023534012974:ios:2e5e22f40d84ad810a9dbf',
    messagingSenderId: '1023534012974',
    projectId: 'imdf-36f5a',
    storageBucket: 'imdf-36f5a.appspot.com',
    iosClientId: '1023534012974-2lnv246n92p1ephrubu8u9r56iobolrl.apps.googleusercontent.com',
    iosBundleId: 'com.example.imdf',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEtM6xoQUSmwLPv44yF1ixNKBARvJ1Nng',
    appId: '1:1023534012974:ios:2e5e22f40d84ad810a9dbf',
    messagingSenderId: '1023534012974',
    projectId: 'imdf-36f5a',
    storageBucket: 'imdf-36f5a.appspot.com',
    iosClientId: '1023534012974-2lnv246n92p1ephrubu8u9r56iobolrl.apps.googleusercontent.com',
    iosBundleId: 'com.example.imdf',
  );
}
